TRENDING_DATA = '/Users/Faisal/Development/recommender-storage/models/trending.data'
POPULAR_DATA = '/Users/Faisal/Development/recommender-storage/models/popular.data'
GENERIC_DATA = '/Users/Faisal/Development/recommender-storage/models/generic.data'
CONTENT_BASED_DATA = '/Users/Faisal/Development/recommender-storage/models/content_based.data'
SIMILARITY_MATRIX = '/Users/Faisal/Development/recommender-storage/models/similarity.matrix'
